// ============================================================
// Two translators, one language switch.
//
//   t(key, vars?) — strings authored in code (UI chrome). The key IS
//                   the English text; Spanish comes from UI_ES.
//   tr(text)      — prose generated by the sim. The world stores its
//                   history in canonical English; tr() translates at
//                   display time by matching the finite set of
//                   templates the sim writes with. This keeps the
//                   simulation state language-neutral, so the same
//                   world can be read in either language and the
//                   deterministic RNG stream is never touched.
// ============================================================
import { UI_ES, UI_ES_F, PHRASES_ES, PHRASES_ES_F, PHRASES_ES_M, RULES_ES, RULES_ES_F } from './i18n-es';

export type Gender = 'm' | 'f';

export type Lang = 'en' | 'es';

let lang: Lang = 'en';
const listeners: (() => void)[] = [];

export function initLang() {
  try {
    const saved = localStorage.getItem('lw:lang');
    if (saved === 'en' || saved === 'es') {
      lang = saved;
      return;
    }
  } catch {
    /* storage may be unavailable; keep default */
  }
  lang = 'es'; // the house language — English is one click away
}

export function getLang(): Lang {
  return lang;
}

export function setLang(l: Lang) {
  if (l === lang) return;
  lang = l;
  try {
    localStorage.setItem('lw:lang', l);
  } catch {
    /* ignore */
  }
  trCache.clear();
  for (const cb of listeners) cb();
}

export function onLangChange(cb: () => void) {
  listeners.push(cb);
}

// ---------------- UI strings ----------------

export function t(key: string, vars?: Record<string, string | number>): string {
  let out = lang === 'en' ? key : UI_ES[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) out = out.split(`{${k}}`).join(String(v));
  }
  return out;
}

/** like t(), but picks the feminine Spanish form when the subject is a woman */
export function tg(key: string, g: Gender): string {
  if (lang === 'en') return key;
  return (g === 'f' ? UI_ES_F[key] : undefined) ?? UI_ES[key] ?? key;
}

// ---------------- generated prose ----------------

interface CompiledRule {
  re: RegExp;
  /** longest literal chunk — cheap pre-filter before the regex runs */
  sig: string;
  slots: string[];
  es: string;
  /** feminine Spanish form, where participles/adjectives refer to the subject */
  esF?: string;
  literalLen: number;
}

let compiled: CompiledRule[] | null = null;

function compileRules(): CompiledRule[] {
  const out: CompiledRule[] = [];
  for (const [en, es] of RULES_ES) {
    const parts = en.split(/\{(\w+)\}/g); // literal, slot, literal, slot, ...
    const slots: string[] = [];
    let re = '^';
    let sig = '';
    let literalLen = 0;
    for (let i = 0; i < parts.length; i++) {
      if (i % 2 === 0) {
        const lit = parts[i];
        literalLen += lit.length;
        if (lit.length > sig.length) sig = lit;
        re += lit.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      } else {
        slots.push(parts[i]);
        // lazy everywhere except the final slot, so literal separators bind first
        re += i === parts.length - 2 && parts[parts.length - 1] === '' ? '([\\s\\S]+)' : '([\\s\\S]+?)';
      }
    }
    re += '$';
    out.push({ re: new RegExp(re), sig, slots, es, esF: RULES_ES_F[en], literalLen });
  }
  // more specific rules first: literal content counts, and each slot adds
  // structure too — otherwise a long-literal one-slot rule (a mutation
  // reason) can swallow a whole composed line it appears inside of
  const spec = (r: CompiledRule) => r.literalLen + r.slots.length * 10;
  out.sort((a, b) => spec(b) - spec(a));
  return out;
}

const trCache = new Map<string, string>();

/** Spanish uses “de el” → “del”, “a el” → “al” */
function contract(s: string): string {
  return s.replace(/\bde el /g, 'del ').replace(/\ba el /g, 'al ');
}

function trFragment(text: string, depth: number, g?: Gender): string {
  if (depth > 4 || text.length === 0) return text;

  const gendered = g === 'f' ? PHRASES_ES_F[text] : g === 'm' ? PHRASES_ES_M[text] : undefined;
  const exact = gendered ?? PHRASES_ES[text];
  if (exact !== undefined) return exact;

  if (!compiled) compiled = compileRules();
  for (const rule of compiled) {
    if (rule.sig && !text.includes(rule.sig)) continue;
    const m = rule.re.exec(text);
    if (!m) continue;
    let out = (g === 'f' ? rule.esF : undefined) ?? rule.es;
    for (let i = 0; i < rule.slots.length; i++) {
      out = out.split(`{${rule.slots[i]}}`).join(trFragment(m[i + 1], depth + 1, g));
    }
    return out;
  }

  // sim sometimes capitalizes a known phrase mid-composition (“The grey fever breaks out…”)
  if (/^[A-Z]/.test(text)) {
    const lower = text[0].toLowerCase() + text.slice(1);
    const viaLower =
      PHRASES_ES[lower] !== undefined ? PHRASES_ES[lower] : depth < 4 ? trFragment(lower, depth + 1, g) : lower;
    if (viaLower !== lower) return viaLower.charAt(0).toUpperCase() + viaLower.slice(1);
  }

  return text;
}

/**
 * translate one line of sim-generated prose; returns the input untouched in
 * English mode. Pass the subject's gender where known (a person's own sheet)
 * so participles and adjectives agree.
 */
export function tr(text: string, g?: Gender): string {
  if (lang === 'en' || !text) return text;
  const key = g === 'f' ? `♀${text}` : text;
  const hit = trCache.get(key);
  if (hit !== undefined) return hit;
  const out = contract(trFragment(text, 0, g));
  if (trCache.size > 6000) trCache.clear();
  trCache.set(key, out);
  return out;
}
